services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: ${DJANGO_DB_NAME}
      POSTGRES_USER: ${DJANGO_DB_USER}
      POSTGRES_PASSWORD: ${DJANGO_DB_PASSWORD}
    ports:
      - "5432:5432"

  django:
    build: ./admin
    ports:
      - "8000:8000"
    volumes:
      - ./admin:/code
      - ./.env:/code/.env:ro s
    environment:
      - DEBUG=1
      - DJANGO_DB_HOST=${DJANGO_DB_HOST}
      - DJANGO_DB_NAME=${DJANGO_DB_NAME}
      - DJANGO_DB_USER=${DJANGO_DB_USER}
      - DJANGO_DB_PASSWORD=${DJANGO_DB_PASSWORD}
    depends_on:
      - db

  angular:
    image: node:20
    build: ./user
    volumes:
      - ./user:/app
      - ./.env:/app/.env:ro
    ports:
      - "4200:4200" # Порт, на котором будет доступно Angular приложение
#      - "9876:9876"
    environment:
      - API_URL=http://${DJANGO_API_HOST}:8000/api
    depends_on:
      - django
volumes:
  postgres_data:
  static_volume:
